name: test & maybe release
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*
    - uses: actions/cache@v2
      id: cache
      env:
        CACHE_NAME: cache-node-modules
      with:
        path: |
          ~/.npm
          ./dist
          ./node_modules
          ./packages/*/dist
          ./packages/*/node_modules
        key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.sha }}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
          npm install
          npm run --if-present build
    - run: npm run --if-present lint
    - run: npm run --if-present dep-check

  test-node:
    needs: check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node: [16]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.npm
            ./dist
            ./node_modules
            ./packages/*/dist
            ./packages/*/node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
            npm install
            npm run --if-present build
      - run: npm run --if-present test:node
      - uses: codecov/codecov-action@v1

  test-chrome:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.npm
            ./dist
            ./node_modules
            ./packages/*/dist
            ./packages/*/node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
            npm install
            npm run --if-present build
      - run: npm run --if-present test:chrome

  test-chrome-webworker:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.npm
            ./dist
            ./node_modules
            ./packages/*/dist
            ./packages/*/node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
            npm install
            npm run --if-present build
      - run: npm run --if-present test:chrome-webworker

  test-firefox:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.npm
            ./dist
            ./node_modules
            ./packages/*/dist
            ./packages/*/node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
            npm install
            npm run --if-present build
      - run: npm run --if-present test:firefox

  test-firefox-webworker:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.npm
            ./dist
            ./node_modules
            ./packages/*/dist
            ./packages/*/node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
            npm install
            npm run --if-present build
      - run: npm run --if-present test:firefox-webworker

  test-electron-main:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.npm
            ./dist
            ./node_modules
            ./packages/*/dist
            ./packages/*/node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
            npm install
            npm run --if-present build
      - run: npx xvfb-maybe npm run --if-present test:electron-main

  test-electron-renderer:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.npm
            ./dist
            ./node_modules
            ./packages/*/dist
            ./packages/*/node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
            npm install
            npm run --if-present build
      - run: npx xvfb-maybe npm run --if-present test:electron-renderer

  release:
    needs: [test-node, test-chrome, test-chrome-webworker, test-firefox, test-firefox-webworker, test-electron-main, test-electron-renderer]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.npm
            ./dist
            ./node_modules
            ./packages/*/dist
            ./packages/*/node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
            npm install
            npm run --if-present build
      - run: |
            if [[ -n "${DOCKER_TOKEN}" ]] && [[ -n "${DOCKER_USERNAME}" ]]; then
              echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
            fi
            npm run --if-present release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
